### ISSUE TITLE
Exercícios HTML #Week1

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/summer-training-week#1]
Em seu desktop, crie uma pasta chamada **HTMLWEEK1** e salve os arquivos html dos exercícios a seguir. Utilize os comentários da _issue_ para submeter suas dúvidas.

### 1) Crie uma página web que inclua os seguintes elementos:
* título com o seu nome;
* texto com uma pequena introdução sobre quem você é e o que você gosta de fazer;
* lista de links com os sites que você mais gosta de acessar;

### 2) Na página que você criou o exercício anterior, faça a seguinte alteração:
* transforme sua lista de links em uma tabela, exibindo os dados da seguinte forma:
<table>
<tr>
<td>Nome do Item</td>
<td><a href="#">link</a></td>
</tr>
</table>

**Comment by BLuksys79** [comment]
`
Exercicio Week 1 - não sei se era assim para enviar porem segue anexo como zip

`
[HTMLWEEK1- BrunaLuksys.zip](https://github.com/WoMakersCode/summer-training-week/files/722168/HTMLWEEK1-.BrunaLuksys.zip)

**Comment by cyz** [comment]
@BLuksys79, vamos seguir o que foi combinado na primeira aula? Iremos disponibilizar uma ferramenta para submissão dos exercícios que serão postados no github após a finalização do curso de github. O que acha? Com a submissão lá, conseguiremos validar para você ganhar um certificado no final.

**Comment by BLuksys79** [comment]
Olá  Cynthia...

Me perdoe, acredito que não tenha compreendido direito como seria feita
essa submissão dos exercícios.
Agora ficou mais claro.
Obrigada e me perdoe !
Foi pura ansiedade e falta de atenção!

Bruna Luksys
11 99871-2070


Em 23 de jan de 2017 2:08 PM, "Cynthia Zanoni" <notifications@github.com>
escreveu:

@BLuksys79 <https://github.com/BLuksys79>, vamos seguir o que foi combinado
na primeira aula? Iremos disponibilizar uma ferramenta para submissão dos
exercícios que serão postados no github após a finalização do curso de
github. O que acha? Com a submissão lá, conseguiremos validar para você
ganhar um certificado no final.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WoMakersCode/summer-training-week/issues/1#issuecomment-274530754>,
or mute the thread

**Comment by cyz** [comment]
@BLuksys79 revisei seu exercício hoje e está tudo certo! :)
